import {Champion} from './champion-base.interface';


export const CHAMPIONS: Champion[] = [
  {
    id: 1,
    name: 'Jinx',
    title: 'the loose canon',
    faction: 'Piltover',
    role: 'Marksman',
    release: 2013.10,
    passive: 'Get Excited!',
    abilities: [
      {shortcut: "q", name: "Switcheroo", description: "blabla", maxlevel: 5},
      {shortcut: "w", name: "Zap", description: "blabla", maxlevel: 5},
      {shortcut: "e", name: "Flame Chompers", description: "blabla", maxlevel: 5},
      {shortcut: "r", name: "Super Mega Death Rocket", description: "blabla", maxlevel: 3},
    ],
    health: 518,
    healthregeneration: 6.97,
    mana: 348,
    manaregeneration: 8.95,
    attackrange: 525,
    attackdamag: 63.9,
    attackspeed: 0.625,
    armor: 30.8,
    magicresist: 31.1,
    movementspeed: 325
  },
  {
    id: 2,
    name: 'Ahri',
    title: 'the nine tailed fox',
    faction: 'Ionia',
    role: 'Mage, Assassin',
    release: 2011.12,
    passive: 'Essence Theft',
    abilities: [
      {shortcut: "q", name: "Switcheroo", description: "blabla", maxlevel: 5},
      {shortcut: "w", name: "Zap", description: "blabla", maxlevel: 5},
      {shortcut: "e", name: "Flame Chompers", description: "blabla", maxlevel: 5},
      {shortcut: "r", name: "Super Mega Death Rocket", description: "blabla", maxlevel: 3},
    ],
    health: 514,
    healthregeneration: 6.508,
    mana: 334,
    manaregeneration: 6,
    attackrange: 550,
    attackdamag: 53.04,
    attackspeed: 0.668,
    armor: 20.88,
    magicresist: 30,
    movementspeed: 330
  },
  {
    id: 3,
    name: 'Thresh',
    title: 'the chain warden',
    faction: 'Shadow Isles',
    role: 'Catcher',
    release: 2013.01,
    passive: 'Damnation',
    abilities: [
      {shortcut: "q", name: "Death Sentence", description: "blabla", maxlevel: 5},
      {shortcut: "w", name: "Dark Passage", description: "blabla", maxlevel: 5},
      {shortcut: "e", name: "Flay", description: "blabla", maxlevel: 5},
      {shortcut: "r", name: "The Box", description: "blabla", maxlevel: 3},
    ],
    health: 561,
    healthregeneration: 6.92,
    mana: 274,
    manaregeneration: 6,
    attackrange: 450,
    attackdamag: 47.7,
    attackspeed: 0.625,
    armor: 16,
    magicresist: 30,
    movementspeed: 335
  },
  {
    id: 4,
    name: 'Tahm Kench',
    title: 'the river king',
    faction: 'Unknown',
    role: 'Warden',
    release: 2015.07,
    passive: 'An Acquired Taste',
    abilities: [
      {shortcut: "q", name: "Tongue Lash", description: "blabla", maxlevel: 5},
      {shortcut: "w", name: "Devour", description: "blabla", maxlevel: 5},
      {shortcut: "e", name: "Thick Skin", description: "blabla", maxlevel: 5},
      {shortcut: "r", name: "Abyssal Voyage", description: "blabla", maxlevel: 3},
    ],
    health: 610,
    healthregeneration: 6.5,
    mana: 325,
    manaregeneration: 8,
    attackrange: 175,
    attackdamag: 56,
    attackspeed: 0.658,
    armor: 27,
    magicresist: 32.1,
    movementspeed: 335
  },
  {
    id: 5,
    name: 'Orianna',
    title: 'the lady of clockwork',
    faction: 'Piltover',
    role: 'Mage',
    release: 2011.06,
    passive: 'Clockwork Windup',
    abilities: [
      {shortcut: "q", name: "Command Attack", description: "blabla", maxlevel: 5},
      {shortcut: "w", name: "Command Dissonance", description: "blabla", maxlevel: 5},
      {shortcut: "e", name: "Command Protect", description: "blabla", maxlevel: 5},
      {shortcut: "r", name: "Command Shockwave", description: "blabla", maxlevel: 3},
    ],
    health: 518,
    healthregeneration: 6.87,
    mana: 334,
    manaregeneration: 6,
    attackrange: 525,
    attackdamag: 40.4,
    attackspeed: 0.658,
    armor: 17,
    magicresist: 30,
    movementspeed: 325
  },
];
